### ISSUE TITLE
How does one get the API key and the Journal ID

### ISSUE THREAD

**Issue by jeffpfoster** [oliyh/tinybeans-archive#1]
These two pieces required to run the code could be added in the README

**Comment by oliyh** [comment]
Hi @jeffpfoster,

The journal id you can see in the URL if you visit your account on tinybeans.com.

The API key I obtained by observing the traffic between my computer and tinybeans. I can't remember if it was just in Chrome developer console or if I had to use wireshark or similar. Does this help?

Oliy

**Comment by jeffpfoster** [comment]
accessToken from the cookie will be the <API_KEY> and Journal Id is in the URL as you mentioned

**Comment by oliyh** [comment]
Belated thanks, I've added this info to the readme
